CREATE TABLE IF NOT EXISTS API_WEBHOOK
(
    ID                          BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    CLIENT_ID                   TEXT  NOT NULL,
    EVENT_TYPE                  TEXT   NOT NULL,
    CALLBACK_URL                TEXT NOT NULL,
    USE_AUTHENTICATION          BOOLEAN  DEFAULT FALSE,
    TOKEN_URL                   TEXT ,
    REFRESH_URL                 TEXT,
    AUD                         TEXT
);

CREATE TABLE IF NOT EXISTS API_ORCHESTRATOR_MESSAGE
(
    ID                          BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    STATUS                      smallint NOT NULL,
    DISTRIBUTION_TYPE           smallint ,
    ORIGIN                      TEXT,
    DESTINATIONS                TEXT,
    MESSAGE_ID                  UUID NOT NULL UNIQUE,
    MESSAGE_TYPE                smallint NOT NULL,
    MESSAGE                     TEXT NOT NULL,
    VALID                       BOOLEAN DEFAULT TRUE
);

CREATE TABLE IF NOT EXISTS API_EVENT_TYPE
(
    ID                BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    EVENT_TYPE        TEXT NOT NULL,
    RML               TEXT NOT NULL,
    SHACL             TEXT,
    SCHEMA_DEFINITION TEXT
);

CREATE TABLE IF NOT EXISTS API_EVENT_DISTRIBUTION_RULE
(
    ID                BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    RULE_TYPE         smallint           NOT NULL,
    DESTINATIONS      TEXT
);

CREATE UNIQUE INDEX IF NOT EXISTS API_EVENT_TYPE_IDX ON API_EVENT_TYPE (EVENT_TYPE);

CREATE TABLE IF NOT EXISTS API_USERS
(
    ID                BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    USERNAME          TEXT NOT NULL,
    PASSWORD          TEXT NOT NULL,
    ROLES             TEXT NOT NULL,
    ISENABLED         BOOLEAN DEFAULT TRUE
);

CREATE UNIQUE INDEX IF NOT EXISTS API_USERS_IDX ON API_USERS (USERNAME);

CREATE TABLE IF NOT EXISTS API_APIKEYS
(
    ID                BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    APIKEY            TEXT NOT NULL,
    ROLES             TEXT NOT NULL,
    ISENABLED         BOOLEAN DEFAULT TRUE
);

CREATE UNIQUE INDEX IF NOT EXISTS API_APIKEYS_IDX ON API_APIKEYS (APIKEY);


ALTER TABLE API_ORCHESTRATOR_MESSAGE ADD COLUMN IF NOT EXISTS ORIGINALJSON TEXT;
ALTER TABLE API_ORCHESTRATOR_MESSAGE ADD COLUMN IF NOT EXISTS EVENTTYPE TEXT;
ALTER TABLE API_ORCHESTRATOR_MESSAGE ADD COLUMN IF NOT EXISTS RECORDED_TIME BIGINT;


